n = input('Digite algo = ')
print(type(n))
alp = (n.isalpha())
num = (n.isalnum())
dec = (n.isdecimal())
esp = (n.isspace())
mai = (n.isupper())
min = (n.islower())
print('É alfabeto? {}'.format(alp))
print('É numérico? {}'.format(num))
print('É decimal? {}'.format(dec))
print('É espaço? {}'.format(esp))
print('É maiúscula? {}'.format(mai))
print('É minúscula? {}'.format(min))
